checkout: rework rebase strategy
Signed-off-by: Jorge Marques <jorge.marques@analog.com>

diff --git a/checkout/action.yml b/checkout/action.yml
--- a/checkout/action.yml
+++ b/checkout/action.yml
@@ -7,7 +7,6 @@ inputs:
     default: ${{ github.token }}
 
 # behaviour:
-# github.event.pull_request.head.sha is always used to detect the PR case.
 # cache/ branches are created to avoid base refs from being garbage collected.
 # on PRs, the github automatic merge commit is flattened, allowing to check per commit.
 
@@ -43,7 +42,7 @@ runs:
           git reset --hard --quiet
           git clean -ffdx --quiet .
 
-          git switch -d || true
+          git switch -d 2>/dev/null || true
           echo "clean-up branches"
           branches=$((git branch || true) | (grep -v ^'*' | grep -v ^'\s\+cache/' | grep -v ^'\s\+mirror/' || true))
           if [[ "$branches" ]]; then
@@ -63,35 +62,40 @@ runs:
       shell: bash
       run: |
         # Get commit depth
-        if [[ "${{ github.event.pull_request.head.sha }}" ]]; then
+        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
           echo "setting fetch_depth based on github.event.pull_request.head.sha"
           json=$(curl -s -L \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ inputs.gh-token }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/repos/${{ github.repository }}/compare/${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}" \
-          | jq '{behind_by, ahead_by}')
+          | jq '{behind_by, ahead_by, merge_base_sha: .merge_base_commit.sha}')
           ahead_by=$(echo $json | jq '.ahead_by')
           behind_by=$(echo $json | jq '.behind_by')
-          if [[ "$ahead_by" == "null" ]]; then
-            echo "GitHub API failed, setting based on github.event.pull_request.commits + 100"
-            ahead_by=${{ github.event.pull_request.commits }}
-            fetch_depth=$(( ahead_by + 100 ))
+          merge_base_sha=$(echo $json | jq '.merge_base_sha')
+          if [[ "$merge_base_sha" == "null" ]]; then
+            echo "::warning ::GitHub API failed to determine merge base sha, will checkout merge commit."
+            echo "fetch_depth=2" >> $GITHUB_ENV
+            echo "checkout_fallback=true" >> $GITHUB_ENV
           else
             fetch_depth=$(( ahead_by + behind_by + 2 ))
+            echo "behind_by=$behind_by" >> $GITHUB_ENV
+            echo "merge_base_sha=$merge_base_commit" >> $GITHUB_ENV
+            echo "fetch_depth=$fetch_depth" >> $GITHUB_ENV
           fi
-          echo "ahead_by=$ahead_by" >> $GITHUB_ENV
-          echo "behind_by=$behind_by" >> $GITHUB_ENV
-          echo "fetch_depth=$fetch_depth" >> $GITHUB_ENV
         elif [[ ! "${{ github.event.before }}" =~ "0000000000000000" ]] && [[ "${{ github.event.forced }}" == "false" ]]; then
           echo "setting fetch_depth based on github.event.before"
           commits_sha='${{ toJSON(github.event.commits.*.id) }}' ;
           fetch_depth=$(( $(jq <<<"$commits_sha" length) + 1 )) ;
           echo "fetch_depth=$fetch_depth" >> $GITHUB_ENV ;
         else
-          echo "setting fetch_depth as 6 (fallback, either due to force-push, new-branch, or uncaught condition)"
+          if [[ "${{ github.event.before }}" =~ "0000000000000000" ]]; then
+            echo "::notice ::New branch, will set base commit as last 5 commits."
+          else
+            echo "::notice ::Force pushed, will set base commit as last 5 commits."
+          fi
           echo "fetch_depth=6" >> $GITHUB_ENV
-          echo "fetch_depth_fallback=true" >> $GITHUB_ENV
+          echo "checkout_fallback=true" >> $GITHUB_ENV
         fi
 
     - name: Fetch & reset
@@ -107,14 +111,17 @@ runs:
           keep_empty="--keep-empty"
         fi
 
-        if [[ "${{ github.event.pull_request.head.sha }}" ]]; then
-          if [[ "$behind_by" -eq 0 ]]; then
+        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+          if [[ "$checkout_fallback" == "true" ]]; then
+            git fetch origin --depth=$fetch_depth $GITHUB_SHA
+            git reset --hard $GITHUB_SHA
+          elif [[ "$behind_by" -eq 0 ]]; then
             git fetch origin --depth=$fetch_depth ${{ github.event.pull_request.head.sha }}
             git reset --hard ${{ github.event.pull_request.head.sha }}
           else
             git fetch origin --depth=$fetch_depth $GITHUB_SHA
-            git reset --hard $GITHUB_SHA
-            while ! git rebase $keep_empty --rebase-merges @~; do
+            git reset --hard ${{ github.event.pull_request.head.sha }}
+            while ! git rebase --rebase-merges $keep_empty ${{ github.event.pull_request.base.sha }}; do
               git rebase --abort
               echo "deepening by $fetch_depth commits"
               git fetch origin --deepen=$fetch_depth $GITHUB_SHA
@@ -123,34 +130,30 @@ runs:
         else
           git fetch origin --depth=$fetch_depth $GITHUB_SHA
           git reset --hard $GITHUB_SHA
-          ahead_by=$((fetch_depth - 1))
-          echo "ahead_by=$ahead_by" >> $GITHUB_ENV
         fi
 
-        if [[ "${{ github.event.pull_request.head.sha }}" ]]; then
-          echo "base_sha=${{ github.event.pull_request.base.sha }}" >> "$GITHUB_ENV"
+        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+          if [[ "$checkout_fallback" != "true" ]]; then
+            base_sha=${{ github.event.pull_request.base.sha }}
+          else
+            base_sha=$(git rev-parse @~)
+          fi
         else
-          echo "base_sha=$(git rev-parse @~$ahead_by)" >> "$GITHUB_ENV"
-        fi
-
-    - name: Apply fixups
-      shell: bash
-      run: |
-        # Apply fixups
-        git rebase $keep_empty --rebase-merges --autosquash $base_sha \
-          || git rebase --abort || true
-
-    - name: Fill environment
-      shell: bash
-      run: |
-        # Fill environment
-        echo "head_sha=$(git rev-parse @)" >> "$GITHUB_ENV"
-
-        if [[ "${{ github.event.pull_request.head.sha }}" ]]; then
-          if [[ "$behind_by" -ne 0 ]]; then
-            echo "fetch_depth=$(git rev-list --count --first-parent $GITHUB_SHA)" >> "$GITHUB_ENV"
+          if [[ "$checkout_fallback" != "true" ]]; then
+            base_sha=${{ github.event.before }}
+          else
+            base_sha=$(git rev-parse @~$((fetch_depth - 1)))
           fi
         fi
+
+        if [[ "$checkout_fallback" != "true" ]]; then
+          echo "Applying fixups"
+          git rebase $keep_empty --rebase-merges --autosquash $base_sha \
+            || git rebase --abort || true
+        fi
+
+        echo "head_sha=$(git rev-parse @)" >> "$GITHUB_ENV"
+        echo "base_sha=$base_sha" >> "$GITHUB_ENV"
 
     - name: Log commit range
       shell: bash
@@ -162,7 +165,7 @@ runs:
       shell: bash
       run: |
         # Generate cache branches & rename
-        if [[ "${{ github.event.pull_request.base.sha }}" ]]; then
+        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
           branch=${{ github.base_ref }}
           commit=${{ github.event.pull_request.base.sha }}
         else
