checkout: rewrite
Key change: pull request open has higher precedence. If it is a push
event, check if a pull request is open, if so, use the pr range instead.

Signed-off-by: Jorge Marques <jorge.marques@analog.com>

diff --git a/checkout/action.yml b/checkout/action.yml
--- a/checkout/action.yml
+++ b/checkout/action.yml
@@ -1,16 +1,13 @@
 name: Git Checkout
-description: A git checkout for local runners and runs
+description: A git checkout for local runners
 
 inputs:
   repository:
     description: "Repository to checkout"
     default: ${{ github.repository }}
-  base-sha:
-    description: "Base SHA for fetch depth"
-    required: false
-  head-sha:
-    description: "Head SHA to checkout"
-    required: false
+  ref:
+    description: "The branch, tag, SHA, or PR number (e.g. 123 or pull/123) to resolve"
+    default: ${{ github.event.pull_request.number || github.sha }}
   gh-token:
     description: "GitHub Token"
     default: ${{ github.token }}
@@ -21,24 +18,104 @@ inputs:
     description: "Enable Git LFS"
     default: 'false'
 
+outputs:
+  pr:
+    description: "Pull request number"
+    value: ${{ steps.resolve.outputs.pr }}
+  head_sha:
+    description: "Head commit sha"
+    value: ${{ steps.checkout.outputs.head_sha }}
+  base_sha:
+    description: "Base commit sha"
+    value: ${{ steps.checkout.outputs.base_sha }}
+  checkout_fail_pr_rebase:
+    description: "Set to true if PR rebase failed"
+    value: ${{ steps.checkout.outputs.checkout_fail_pr_rebase }}
+  checkout_fail_pr_fixup:
+    description: "Set to true if PR fixup failed"
+    value: ${{ steps.checkout.outputs.checkout_fail_pr_fixup }}
 
-# behaviour:
-# cache/ branches are created to avoid base refs from being garbage collected.
-# on PRs, the github automatic merge commit is flattened, allowing to check per commit.
-# if head-sha is set, uses simple fetch flow (for external repos, including
-# submodules, or workflow_dispatch).
+# Behaviour:
+# If a PR is associated with the ref, it is used:
+# - The history is rebased into the target branch head (fail -> checkout_fail_pr_rebase)
+# - Fixup commits are auto squashed (fail -> checkout_fail_pr_fixup)
+# If no PR is associated, just checkout N commits.
 
 runs:
   using: composite
   steps:
-    - name: Sanity check
+    - name: Resolve ref to PR
+      id: resolve
       shell: bash
       run: |
-        # Sanity check
-        if [[ -z "${{ inputs.head-sha }}" ]] && [[ -n "${{ inputs.base-sha }}" ]]; then
-          echo "::error ::Cannot set base-sha without specifying a head-sha."
-          exit 1
+        # Resolve ref to PR
+        [[ "${{ runner.debug }}" == "1" ]] && set -x
+
+        ref="${{ inputs.ref }}"
+        repository="${{ inputs.repository }}"
+
+        branch=
+        resp=
+        pr_json=
+        pr=
+
+        if [[ "${{ inputs.repository }}" =~ ^(git@|ssh://|https://) ]]; then
+          exit 0
         fi
+
+        if ! [[ "$ref" =~ ^([0-9]+|pull/[0-9]+)(/head)?$ ]]; then
+          # branch/commit
+
+          # try branch
+          branch="${ref#refs/heads/}"
+          [[ "$branch" == *":"* ]] || {
+            owner="${repository%/*}"
+            branch="$owner:$branch"
+          }
+          # some-user:my-fix
+          resp=$(curl -s \
+            -H "Authorization: Bearer ${{ inputs.gh-token }}" \
+            -H "Accept: application/vnd.github+json" \
+            "https://api.github.com/repos/$repository/pulls?head=$branch&state=open")
+
+          pr_json=$(echo "$resp" | jq '.[0]')
+          if [[ "$pr_json" == "null" ]]; then
+            # try sha
+            sha="$ref"
+            resp=$(curl -s \
+              -H "Authorization: Bearer ${{ inputs.gh-token }}" \
+              -H "Accept: application/vnd.github+json" \
+              "https://api.github.com/repos/$repository/commits/$sha/pulls?state=open")
+            pr_json=$(echo "$resp" | jq '.[0]')
+          fi
+
+          pr=$(echo "$pr_json" | jq -r '.number')
+        else
+          # pr number
+          pr="${ref#pull/}"
+          pr="${pr%/head}"
+        fi
+
+        if [[ -n "$pr" ]]; then
+          resp=$(curl -s \
+            -H "Authorization: Bearer ${{ inputs.gh-token }}" \
+            -H "Accept: application/vnd.github+json" \
+            "https://api.github.com/repos/$repository/pulls/$pr")
+          status=$(echo "$resp" | jq -r '.status // empty')
+          if [[ "$status" == "404" ]]; then
+            # does not exist
+            pr=""
+          else
+            merge_commit_sha=$(echo "$resp" | jq -r '.merge_commit_sha')
+            if [[ "$merge_commit_sha" == "null" ]]; then
+              # has conflicts
+              pr=""
+            fi
+          fi
+        fi
+
+        echo "pr=$pr" >> "$GITHUB_OUTPUT"
+        echo "pr=$pr" >> "$GITHUB_ENV"
 
     - name: Prepare git
       shell: bash
@@ -55,7 +132,6 @@ runs:
         elif [ "${{ inputs.lfs }}" = "true" ]; then
           echo "::warning ::Git LFS set to true, but git-lfs is not installed."
         fi
-        # Prepare git
         if [[ "${{ inputs.repository }}" =~ ^(git@|ssh://|https://) ]]; then
           url="${{ inputs.repository }}"
           org_repository=$(echo "${{ inputs.repository }}" | sed -E 's|.*[:/]([^/]+/[^/.]+)(\.git)?$|\1|')
@@ -95,12 +171,13 @@ runs:
 
           git switch -d 2>/dev/null || true
           echo "clean-up branches"
-          branches=$((git branch || true) | (grep -v ^'*' | grep -v ^'\s\+cache/' | grep -v ^'\s\+mirror/' || true))
+          branches=$((git branch || true) | (grep -v ^'*' || true))
           if [[ "$branches" ]]; then
             git branch -D $branches || true
           fi
-          git switch -C trunk
         fi
+
+        git switch -C trunk
 
         if [[ -z "$(git config user.name)"  ]]; then
           git config user.name "github-actions[bot]"
@@ -108,66 +185,19 @@ runs:
         if [[ -z "$(git config user.email)"  ]]; then
           git config user.email "github-actions[bot]@users.noreply.github.com"
         fi
+        git config gc.auto 0
 
-    - name: Get commit depth
+    - name: Checkout
+      id: checkout
       shell: bash
       run: |
-        # Get commit depth
+        # Checkout
         [[ "${{ runner.debug }}" == "1" ]] && set -x
         cd "${{ inputs.path }}"
 
-        if [[ -n "${{ inputs.head-sha }}" ]]; then
-          head_sha="${{ inputs.head-sha }}"
-          echo "head_sha=$head_sha" >> $GITHUB_ENV
-          echo "fetch_depth=7" >> $GITHUB_ENV
-        elif [[ "${{ inputs.repository }}" == "${{ github.repository }}" ]] && [[ "${{ github.event_name }}" == "pull_request" ]]; then
-          json=$(curl -s -L \
-            -H "Accept: application/vnd.github+json" \
-            -H "Authorization: Bearer ${{ inputs.gh-token }}" \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            "https://api.github.com/repos/${{ github.repository }}/compare/${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}" \
-          | jq '{behind_by, ahead_by, merge_base_sha: .merge_base_commit.sha}')
-          ahead_by=$(echo $json | jq '.ahead_by')
-          behind_by=$(echo $json | jq '.behind_by')
-          merge_base_sha=$(echo $json | jq '.merge_base_sha')
-          if [[ "$merge_base_sha" == "null" ]]; then
-            echo "::warning ::GitHub API failed to determine merge base sha, will checkout merge commit."
-            echo "fetch_depth=3" >> $GITHUB_ENV
-            echo "checkout_fallback=true" >> $GITHUB_ENV
-          else
-            fetch_depth=$(( ahead_by + behind_by + 2 ))
-            echo "behind_by=$behind_by" >> $GITHUB_ENV
-            echo "fetch_depth=$fetch_depth" >> $GITHUB_ENV
-            [ "$fetch_depth" -gt 1000 ] && echo "checkout_fallback=true" >> $GITHUB_ENV || true
-          fi
-        elif [[ "${{ inputs.repository }}" == "${{ github.repository }}" ]] && [[ "${{ github.event_name }}" == "push" ]]; then
-          if [[ ! "${{ github.event.before }}" =~ "0000000000000000" ]] && [[ "${{ github.event.forced }}" == "false" ]]; then
-            echo "setting fetch_depth based on github.event.before"
-            commits_sha='${{ toJSON(github.event.commits.*.id) }}' ;
-            fetch_depth=$(( $(jq <<<"$commits_sha" length) + 1 )) ;
-            echo "fetch_depth=$fetch_depth" >> $GITHUB_ENV ;
-          else
-            if [[ "${{ github.event.before }}" =~ "0000000000000000" ]]; then
-              echo "::notice ::New branch, will set base commit as last 5 commits."
-            else
-              echo "::notice ::Force pushed, will set base commit as last 5 commits."
-            fi
-            echo "fetch_depth=7" >> $GITHUB_ENV
-            echo "checkout_fallback=true" >> $GITHUB_ENV
-          fi
-        else
-          head_sha=$(git ls-remote origin HEAD | awk '{print $1}' | tail -1)
-          echo "head_sha=$head_sha" >> $GITHUB_ENV
-          echo "fetch_depth=3" >> $GITHUB_ENV
-        fi
+        repository="${{ inputs.repository }}"
+        pr="${{ steps.resolve.outputs.pr }}"
 
-    - name: Fetch & reset
-      shell: bash
-      run: |
-        # Fetch & reset
-        [[ "${{ runner.debug }}" == "1" ]] && set -x
-        cd "${{ inputs.path }}"
-        _fetch_depth=$(( fetch_depth > 500 ? 500 : fetch_depth ))
         # --empty was added on git 2.26.0
         has_keep=$(git rebase -help 2>&1 | grep "\--empty" | wc -l) || true
         if [[ "$has_keep" -gt "0" ]]; then
@@ -176,89 +206,64 @@ runs:
           keep_empty="--keep-empty"
         fi
 
-        if [[ -n "$head_sha" ]]; then
-          git fetch origin --depth=$_fetch_depth $head_sha
-          git reset --hard FETCH_HEAD
-          if [[ -n "${{ inputs.base-sha }}" ]]; then
-            base_sha="${{ inputs.base-sha }}"
-          else
-            base_sha="$head_sha~$((_fetch_depth - 2))"
-          fi
-        elif [[ "${{ inputs.repository }}" == "${{ github.repository }}" ]] && [[ "${{ github.event_name }}" == "pull_request" ]]; then
-          if [[ "$checkout_fallback" == "true" ]]; then
-            git fetch origin --depth=$_fetch_depth ${{ github.sha }}
-            git reset --hard FETCH_HEAD
-          elif [[ "$behind_by" -eq 0 ]]; then
-            git fetch origin --depth=$_fetch_depth ${{ github.event.pull_request.head.sha }}
-            git reset --hard FETCH_HEAD
-          else
-            echo "Fetching commits in batches of $_fetch_depth"
-            while ! git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} &>/dev/null ; do
-              git fetch origin --deepen=$_fetch_depth ${{ github.sha }}
-            done
-            git reset --hard ${{ github.event.pull_request.base.sha }}
-            git rebase --rebase-merges $keep_empty ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
-            git switch -C trunk
-          fi
-          head_sha=$(git rev-parse @)
-          if [[ "$checkout_fallback" == "true" ]]; then
-            base_sha="@~"
-          else
-            base_sha=${{ github.event.pull_request.base.sha }}
-          fi
-        elif [[ "${{ inputs.repository }}" == "${{ github.repository }}" ]] && [[ "${{ github.event_name }}" == "push" ]]; then
-          git fetch origin --depth=$_fetch_depth ${{ github.sha }}
-          git reset --hard FETCH_HEAD
-          head_sha=$(git rev-parse @)
-          if [[ "$checkout_fallback" == "true" ]]; then
-            base_sha="@~$((_fetch_depth - 2))"
-          else
-            base_sha=${{ github.event.before }}
-          fi
-        fi
+        fetch_depth=7
+        if [[ -n "$pr" ]]; then
+          mode="pr"
+          git fetch origin --depth=1 "refs/pull/$pr/merge"
+          fetch_head=$(git rev-parse FETCH_HEAD)
 
-        while ! git rev-list --count $base_sha~..$head_sha ; do
-          git fetch origin --deepen=$_fetch_depth $head_sha
-          git fetch origin --deepen=$_fetch_depth $base_sha
-        done
-        base_sha=$(git rev-parse $base_sha)
+          while ! git merge-base $fetch_head^1 $fetch_head^2 ; do
+            git fetch origin --deepen=$fetch_depth $fetch_head
+          done
 
-        if [[ "$checkout_fallback" == "true" ]]; then
-          :
-        elif git log --oneline --pretty=format:'%s' $base_sha..$head_sha | grep ^fixup! ; then
-          echo "Has fixups! in range, applying"
-          git rebase $keep_empty --rebase-merges --autosquash $base_sha \
-            || git rebase --abort || true
+          head_sha=$(git rev-parse $fetch_head^2)
+          into_head_sha=$(git rev-parse $fetch_head^1)
+          base_sha=$(git rev-list --reverse $into_head_sha..$head_sha | head -n 1)
+          base_sha=$(git rev-parse $base_sha~)
         else
-          echo "No fixups! in range"
+          mode="branch"
+          git fetch origin --depth=$fetch_depth "${{ inputs.ref }}"
+
+          head_sha=$(git rev-parse "${{ inputs.ref }}")
+          base_sha=$(git rev-parse $head_sha~$fetch_depth)
         fi
-        head_sha=$(git rev-parse @)
+
+        git reset --hard FETCH_HEAD
+
+        if [[ "$mode" == "pr" ]]; then
+          # rebase into
+          git rebase --rebase-merges "$keep_empty" \
+            "$into_head_sha" "$head_sha" && {
+            head_sha=$(git rev-parse HEAD)
+            base_sha=$into_head_sha
+          } || {
+            git rebase --abort
+            checkout_fail_pr_rebase="true"
+          }
+
+          # apply fixups
+          git log --oneline --pretty=format:'%s' $base_sha..$head_sha | grep ^fixup! && {
+            git rebase $keep_empty --rebase-merges --autosquash $base_sha \
+              || git rebase --abort && {
+              head_sha=$(git rev-parse HEAD)
+            } || {
+              git rebase --abort
+              checkout_fail_pr_fixup="true"
+            }
+          } || true
+        fi
+
+        git log --oneline --reverse $base_sha..$head_sha
+
+        git branch -m $branch 2>/dev/null || true
+
+        echo "head_sha=$head_sha" >> "$GITHUB_OUTPUT"
+        echo "base_sha=$base_sha" >> "$GITHUB_OUTPUT"
+        echo "checkout_fail_pr_rebase=$checkout_fail_pr_rebase" >> "$GITHUB_OUTPUT"
+        echo "checkout_fail_pr_fixup=$checkout_fail_pr_fixup" >> "$GITHUB_OUTPUT"
 
         echo "head_sha=$head_sha" >> "$GITHUB_ENV"
         echo "base_sha=$base_sha" >> "$GITHUB_ENV"
+        echo "checkout_fail_pr_rebase=$checkout_fail_pr_rebase" >> "$GITHUB_ENV"
+        echo "checkout_fail_pr_fixup=$checkout_fail_pr_fixup" >> "$GITHUB_ENV"
 
-    - name: Log commit range
-      shell: bash
-      run: |
-        # Log commit range
-        [[ "${{ runner.debug }}" == "1" ]] && set -x
-        cd "${{ inputs.path }}"
-        git log --oneline --reverse $base_sha..$head_sha
-
-    - name: Generate cache branches & rename
-      shell: bash
-      if: ${{ github.repository == inputs.repository && inputs.head-sha == '' }}
-      run: |
-        # Generate cache branches & rename
-        [[ "${{ runner.debug }}" == "1" ]] && set -x
-        cd "${{ inputs.path }}"
-        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
-          branch=${{ github.base_ref }}
-          commit=${{ github.event.pull_request.base.sha }}
-        else
-          branch=${{ github.ref_name }}
-          commit=$head_sha
-        fi
-        git branch cache/$branch $commit -f
-        git branch -m $branch 2>/dev/null || true
-        git --no-pager branch
