actions: checkout: set ahead_by, reorganize logic
Signed-off-by: Jorge Marques <jorge.marques@analog.com>

diff --git a/ci/actions/checkout/action.yml b/ci/actions/checkout/action.yml
--- a/ci/actions/checkout/action.yml
+++ b/ci/actions/checkout/action.yml
@@ -2,11 +2,8 @@ name: Git Checkout
 description: A git checkout for local runners and runs
 
 inputs:
-  depth:
-    description: The depth when fetching
-    required: false
   gh-token:
-    description: 'GitHub Token'
+    description: "GitHub Token"
     default: ${{ github.token }}
 
 # behaviour:
@@ -17,32 +14,14 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: Get commit depth
-      shell: bash
-      run: |
-        if [[ "${{ inputs.depth }}" ]]; then
-          echo "setting fetch_depth based on inputs.depth"
-          echo "fetch_depth=$(( ${{ inputs.depth }} + 1 ))" >> $GITHUB_ENV
-        elif [[ "${{ github.event.pull_request.commits }}" ]]; then
-          echo "setting fetch_depth based on github.event.pull_request.commits"
-          echo "fetch_depth=$(( ${{ github.event.pull_request.commits }} + 2 ))" >> $GITHUB_ENV
-        elif [[ ! "${{ github.event.before }}" =~ "0000000000000000" ]] && [[ "${{ github.event.forced }}" == "false" ]]; then
-          echo "setting fetch_depth based on github.event.before"
-          commits_sha='${{ toJSON(github.event.commits.*.id) }}' ;
-          fetch_depth=$(( $(jq <<<"$commits_sha" length) + 1 )) ;
-          echo "fetch_depth=$fetch_depth" >> $GITHUB_ENV ;
-        else
-          echo "setting fetch_depth as 6 (fallback, either due to force-push, new-branch, or uncaught condition)"
-          echo "fetch_depth=6" >> $GITHUB_ENV
-          echo "fetch_depth_fallback=true" >> $GITHUB_ENV
-        fi
-
-        echo "head_sha=$GITHUB_SHA" >> $GITHUB_ENV
-
     - name: Prepare git
       shell: bash
       run: |
         url="https://x-access-token:${{ inputs.gh-token }}@github.com/${{ github.repository }}.git"
+
+        if [[ -f .git/shallow.lock ]] || [[ -f .git/index.lock ]]; then
+          rm -rf .* *
+        fi
 
         if [[ ! -d .git ]]; then
           git init --initial-branch=trunk .
@@ -78,19 +57,50 @@ runs:
           git config user.email "github-actions[bot]@users.noreply.github.com"
         fi
 
-    - name: Fetch
+    - name: Get commit depth
       shell: bash
       run: |
-        git fetch origin --depth=$fetch_depth $head_sha
-        avail_depth=$(git rev-list --count $head_sha)
+        if [[ "${{ github.event.pull_request.head.sha }}" ]]; then
+          echo "setting fetch_depth based on github.event.pull_request.head.sha"
+          json=$(curl -s -L \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ inputs.gh-token }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/${{ github.repository }}/compare/${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }}" \
+          | jq '{behind_by, ahead_by}')
+          ahead_by=$(echo $json | jq '.ahead_by')
+          behind_by=$(echo $json | jq '.behind_by')
+          if [[ "$ahead_by" == "null" ]]; then
+            echo "GitHub API failed, setting based on github.event.pull_request.commits + 100"
+            ahead_by=${{ github.event.pull_request.commits }}
+            echo "ahead_by=$ahead_by" >> $GITHUB_ENV
+            fetch_depth=$(( ahead_by + 100 ))
+          else
+            echo "ahead_by=$ahead_by" >> $GITHUB_ENV
+            fetch_depth=$(( ahead_by + behind_by ))
+          fi
+          echo "fetch_depth=$fetch_depth" >> $GITHUB_ENV
+        elif [[ ! "${{ github.event.before }}" =~ "0000000000000000" ]] && [[ "${{ github.event.forced }}" == "false" ]]; then
+          echo "setting fetch_depth based on github.event.before"
+          commits_sha='${{ toJSON(github.event.commits.*.id) }}' ;
+          fetch_depth=$(( $(jq <<<"$commits_sha" length) + 1 )) ;
+          echo "fetch_depth=$fetch_depth" >> $GITHUB_ENV ;
+        else
+          echo "setting fetch_depth as 6 (fallback, either due to force-push, new-branch, or uncaught condition)"
+          echo "fetch_depth=6" >> $GITHUB_ENV
+          echo "fetch_depth_fallback=true" >> $GITHUB_ENV
+        fi
+
+    - name: Fetch & checkout
+      shell: bash
+      run: |
+        git fetch origin --depth=$fetch_depth $GITHUB_SHA
+        avail_depth=$(git rev-list --count $GITHUB_SHA)
         if [[ $fetch_depth -gt $avail_depth ]]; then
           echo "fetch_depth=$avail_depth" >> $GITHUB_ENV
         fi
 
-    - name: Checkout
-      shell: bash
-      run: |
-        git reset --hard $head_sha
+        git reset --hard $GITHUB_SHA
         if [[ "${{ github.event.pull_request.head.sha }}" ]]; then
           # --empty was added on git 2.26.0
           has_keep=$(git rebase -help 2>&1 | grep "\--empty" | wc -l) || true
@@ -101,20 +111,19 @@ runs:
             keep_empty="--keep-empty"
           fi
           git rebase $keep_empty @~
-          number_commits=$((fetch_depth - 2))
         else
-          number_commits=$((fetch_depth - 1))
+          ahead_by=$((fetch_depth - 1))
+          echo "ahead_by=$ahead_by" >> $GITHUB_ENV
         fi
-        echo "number_commits=$number_commits" >> $GITHUB_ENV
         echo "head_sha=$(git rev-parse @)" >> "$GITHUB_ENV"
-        echo "base_sha=$(git rev-parse @~$number_commits)" >> "$GITHUB_ENV"
+        echo "base_sha=$(git rev-parse @~$ahead_by)" >> "$GITHUB_ENV"
 
     - name: Log commit range
       shell: bash
       run: |
         git log --oneline --reverse $base_sha..$head_sha
 
-    - name: Generate cache branches
+    - name: Generate cache branches & rename
       shell: bash
       run: |
         if [[ "${{ github.event.pull_request.base.sha }}" ]]; then
@@ -126,4 +135,5 @@ runs:
         fi
         cache_branch=cache/$cache_branch
         git branch $cache_branch $cache_commit -f
+        git branch -m $cache_branch || true
         git --no-pager branch
